// ---------------------------------------------------------------------------
// MOCK DATA — mirrors the shape your Marketplace API will return.
// When the backend is ready, marketplace.api.js fetches real JSON
// and this file becomes unused.
// ---------------------------------------------------------------------------

// Swap these out for real product photos: "/assets/products/broilers.jpg"
const IMG = {
  broilers:   "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=700&q=80",
  broilers2:  "https://images.unsplash.com/photo-1585634917202-6f608fd03b67?w=700&q=80",
  layers:     "https://images.unsplash.com/photo-1569400850459-d13fa92e0a5a?w=700&q=80",
  indigenous: "https://images.unsplash.com/photo-1506908260168-3fdc10dfeb53?w=700&q=80",
  eggs:       "https://images.unsplash.com/photo-1518569656558-1f25e69d2fd4?w=700&q=80",
  feed:       "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=700&q=80",
};

// Product shape — keep in sync with your backend DTO
export const MOCK_PRODUCTS = [
  {
    id: "prod_001",
    category: "broilers",
    district: "Maseru",
    village: "Ha Thetsane",
    farmer: {
      id: "farmer_001",
      name: { en: "Nthabiseng Mokoena", st: "Nthabiseng Mokoena" },
      phone: "+26658123456",
      verified: true,
    },
    title:       { en: "Day-old broiler chicks",          st: "Li-pjoana tsa li-broiler" },
    description: {
      en: "Healthy Ross 308 day-old chicks. Vaccinated against Marek's disease. Available every week from our certified hatchery.",
      st: "Li-pjoana tse phelang tsa Ross 308. Li kolosetsa Marek. Li fumaneha beke le beke ho tsoa mothating oa rona.",
    },
    price:    35,
    currency: "LSL",
    unit:     { en: "per chick",    st: "ka pjoana" },
    stock:    500,
    minOrder: 20,
    badge:    { type: "green",  en: "In stock",  st: "E teng" },
    rating:   4.8,
    reviews:  23,
    images:   [IMG.broilers],
    createdAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "prod_002",
    category: "layers",
    district: "Maseru",
    village: "Lithabaneng",
    farmer: {
      id: "farmer_002",
      name: { en: "Thabiso Letsie", st: "Thabiso Letsie" },
      phone: "+26662345678",
      verified: true,
    },
    title:       { en: "Point-of-lay hens (16 wks)",             st: "Likhukhu tse haufi le ho bua mae" },
    description: {
      en: "Lohmann Brown ready-to-lay pullets. Fully vaccinated. Excellent laying history from our parent flock.",
      st: "Li-Lohmann Brown tse loketsoeng ho bua mae. Li kolotsoa kaofela. Nalane e ntle ea ho bua mae.",
    },
    price:    180,
    currency: "LSL",
    unit:     { en: "per bird",   st: "ka nonyana" },
    stock:    120,
    minOrder: 10,
    badge:    { type: "amber", en: "Low stock", st: "E fokola" },
    rating:   4.6,
    reviews:  15,
    images:   [IMG.layers],
    createdAt: "2025-01-12T09:00:00Z",
  },
  {
    id: "prod_003",
    category: "eggs",
    district: "Leribe",
    village: "Hlotse",
    farmer: {
      id: "farmer_003",
      name: { en: "Mamorena Sello", st: "Mamorena Sello" },
      phone: "+26659876543",
      verified: false,
    },
    title:       { en: "Fresh free-range eggs",                   st: "Mae a foreshe a likhukhu tsa ntle" },
    description: {
      en: "Farm-fresh eggs collected daily from free-range layers. Available Mon, Wed, Fri for pickup or delivery within Leribe.",
      st: "Mae a polasi a khokahanoa letsatsi le letsatsi. A fumaneha Msombuluko, Laboraro, Labohlano.",
    },
    price:    28,
    currency: "LSL",
    unit:     { en: "per tray (30)", st: "ka thepe (30)" },
    stock:    200,
    minOrder: 5,
    badge:    { type: "green",  en: "In stock",  st: "E teng" },
    rating:   4.9,
    reviews:  41,
    images:   [IMG.eggs],
    createdAt: "2025-01-14T07:00:00Z",
  },
  {
    id: "prod_004",
    category: "indigenous",
    district: "Berea",
    village: "Teyateyaneng",
    farmer: {
      id: "farmer_004",
      name: { en: "Retselisitsoe Molapo", st: "Retselisitsoe Molapo" },
      phone: "+26663457890",
      verified: true,
    },
    title:       { en: "Indigenous chickens (mature)",             st: "Likhukhu tsa naha (tse holile)" },
    description: {
      en: "Naturally raised Basotho indigenous chickens. No growth hormones, no antibiotics. Sold live or slaughtered on request.",
      st: "Likhukhu tsa Basotho tse holisitsoeng ka tlhaho. Ha ho makhomelo. Li ruisoa kapa li hlatsuoa ha o kopa.",
    },
    price:    120,
    currency: "LSL",
    unit:     { en: "per bird",   st: "ka nonyana" },
    stock:    45,
    minOrder: 3,
    badge:    { type: "green",  en: "In stock",  st: "E teng" },
    rating:   5.0,
    reviews:  8,
    images:   [IMG.indigenous],
    createdAt: "2025-01-08T10:00:00Z",
  },
  {
    id: "prod_005",
    category: "feed",
    district: "Maseru",
    village: "Industrial Area",
    farmer: {
      id: "farmer_005",
      name: { en: "Khokahano Feed Supplies", st: "Khokahano Feed Supplies" },
      phone: "+26622321234",
      verified: true,
    },
    title:       { en: "Broiler starter crumble 25 kg",           st: "Mocha oa li-broiler (25 kg)" },
    description: {
      en: "High-protein starter crumble for day-old to 2-week broilers. 22% protein, enriched with vitamins and minerals.",
      st: "Mocha o nang le protein e ngata bakeng sa li-broiler tse ncha. Protein 22%, le livitamine.",
    },
    price:    320,
    currency: "LSL",
    unit:     { en: "per bag",    st: "ka sekhao" },
    stock:    80,
    minOrder: 1,
    badge:    { type: "green",  en: "In stock",  st: "E teng" },
    rating:   4.7,
    reviews:  56,
    images:   [IMG.feed],
    createdAt: "2025-01-05T11:00:00Z",
  },
  {
    id: "prod_006",
    category: "broilers",
    district: "Berea",
    village: "Mapoteng",
    farmer: {
      id: "farmer_006",
      name: { en: "Lineo Ramaili", st: "Lineo Ramaili" },
      phone: "+26656789012",
      verified: false,
    },
    title:       { en: "Live broilers (5\u20136 weeks)",           st: "Li-broiler tse phelang (beke 5\u20136)" },
    description: {
      en: "Ready-to-slaughter broilers averaging 1.8\u20132.2 kg live weight. Raised on quality feed with strict biosecurity.",
      st: "Li-broiler tse loketsoeng ho hlatsuoa. Boima bo thusang ke kg 1.8\u20132.2. Ts'ireletso e na teng.",
    },
    price:    95,
    currency: "LSL",
    unit:     { en: "per bird",   st: "ka nonyana" },
    stock:    200,
    minOrder: 10,
    badge:    { type: "blue",   en: "Pre-order", st: "Taelo ea pele" },
    rating:   4.5,
    reviews:  19,
    images:   [IMG.broilers2],
    createdAt: "2025-01-16T06:00:00Z",
  },
];

export const MOCK_STATS = {
  totalFarmers:  48,
  totalDistricts: 10,
  totalListings: 230,
  avgRating:     4.8,
};